
/*
Auto-generated by CVXPYgen on August 28, 2025 at 09:53:33.
Content: Example program for updating parameters, solving, and inspecting the result.
*/

#include <stdio.h>
#include "cpg_workspace.h"
#include "cpg_solve.h"

static int i;

int main(int argc, char *argv[]){

  // Update first entry of every user-defined parameter
  cpg_update_Ak_0(0, 1.05388236381908817485);
  cpg_update_Bk_minus_0(0, 0.04651757187110328734);
  cpg_update_Bk_plus_0(0, 0.02330157414146952904);
  cpg_update_ck(0, -0.21328824352022968114);
  cpg_update_Ak_1(0, 1.05500627503479549318);
  cpg_update_Bk_minus_1(0, 0.04937543080551612396);
  cpg_update_Bk_plus_1(0, 0.02475747593231248170);
  cpg_update_Ak_2(0, 1.05030756417419901538);
  cpg_update_Bk_minus_2(0, 0.05246385913389389755);
  cpg_update_Bk_plus_2(0, 0.02634401770092120038);
  cpg_update_Ak_3(0, 1.04159096417862473416);
  cpg_update_Bk_minus_3(0, 0.05593828102539764174);
  cpg_update_Bk_plus_3(0, 0.02814219120371479199);
  cpg_update_Ak_4(0, 1.03064503265494789019);
  cpg_update_Bk_minus_4(0, 0.05990145688647058320);
  cpg_update_Bk_plus_4(0, 0.03020356443247430162);
  cpg_update_Ak_5(0, 1.01893484080448759599);
  cpg_update_Bk_minus_5(0, 0.06448466356645657371);
  cpg_update_Bk_plus_5(0, 0.03259531394978401608);
  cpg_update_Ak_6(0, 1.00752834881828245983);
  cpg_update_Bk_minus_6(0, 0.06985959328331826923);
  cpg_update_Bk_plus_6(0, 0.03540701914315538129);
  cpg_update_Ak_7(0, 0.99718643583481803017);
  cpg_update_Bk_minus_7(0, 0.07625883032084314339);
  cpg_update_Bk_plus_7(0, 0.03876179975908180392);
  cpg_update_Ak_8(0, 0.98854203127858830680);
  cpg_update_Bk_minus_8(0, 0.08401019266692164034);
  cpg_update_Bk_plus_8(0, 0.04283480728682172167);
  cpg_update_Ak_9(0, 0.98229539431228340973);
  cpg_update_Bk_minus_9(0, 0.09359510092893780220);
  cpg_update_Bk_plus_9(0, 0.04788493487144636351);
  cpg_update_Ak_10(0, 0.97935774426635613388);
  cpg_update_Bk_minus_10(0, 0.10575178473759189179);
  cpg_update_Bk_plus_10(0, 0.05431193482742897871);
  cpg_update_Ak_11(0, 0.98087427162052787111);
  cpg_update_Bk_minus_11(0, 0.12166921955981765957);
  cpg_update_Bk_plus_11(0, 0.06276634877580061778);
  cpg_update_Ak_12(0, 0.98805895751823535900);
  cpg_update_Bk_minus_12(0, 0.14338352914160601426);
  cpg_update_Bk_plus_12(0, 0.07438043354770876303);
  cpg_update_Ak_13(0, 1.00259467336376650870);
  cpg_update_Bk_minus_13(0, 0.16223716140184035739);
  cpg_update_Bk_plus_13(0, 0.08231389581825430957);
  cpg_update_x_0(0, 2.41956774020513076806);
  cpg_update_x_f(0, -1.86128255795724495414);
  cpg_update_x_ref(0, 2.41956774020513032397);
  cpg_update_u_ref(0, 0.36631353607617256340);

  // Solve the problem instance
  cpg_solve();

  // Print objective function value
  printf("obj = %f\n", CPG_Result.info->obj_val);

  // Print primal solution
  for(i=0; i<45; i++) {
    printf("U[%d] = %f\n", i, CPG_Result.prim->U[i]);
  }
  for(i=0; i<98; i++) {
    printf("V[%d] = %f\n", i, CPG_Result.prim->V[i]);
  }
  for(i=0; i<7; i++) {
    printf("v_0[%d] = %f\n", i, CPG_Result.prim->v_0[i]);
  }
  for(i=0; i<6; i++) {
    printf("v_N[%d] = %f\n", i, CPG_Result.prim->v_N[i]);
  }
  for(i=0; i<15; i++) {
    printf("eta[%d] = %f\n", i, CPG_Result.prim->eta[i]);
  }
  for(i=0; i<105; i++) {
    printf("X[%d] = %f\n", i, CPG_Result.prim->X[i]);
  }

  // Print dual solution
  for(i=0; i<7; i++) {
    printf("d0[%d] = %f\n", i, CPG_Result.dual->d0[i]);
  }
  for(i=0; i<7; i++) {
    printf("d1[%d] = %f\n", i, CPG_Result.dual->d1[i]);
  }
  for(i=0; i<7; i++) {
    printf("d2[%d] = %f\n", i, CPG_Result.dual->d2[i]);
  }
  for(i=0; i<7; i++) {
    printf("d3[%d] = %f\n", i, CPG_Result.dual->d3[i]);
  }
  for(i=0; i<7; i++) {
    printf("d4[%d] = %f\n", i, CPG_Result.dual->d4[i]);
  }
  for(i=0; i<7; i++) {
    printf("d5[%d] = %f\n", i, CPG_Result.dual->d5[i]);
  }
  for(i=0; i<7; i++) {
    printf("d6[%d] = %f\n", i, CPG_Result.dual->d6[i]);
  }
  for(i=0; i<7; i++) {
    printf("d7[%d] = %f\n", i, CPG_Result.dual->d7[i]);
  }
  for(i=0; i<7; i++) {
    printf("d8[%d] = %f\n", i, CPG_Result.dual->d8[i]);
  }
  for(i=0; i<7; i++) {
    printf("d9[%d] = %f\n", i, CPG_Result.dual->d9[i]);
  }
  for(i=0; i<7; i++) {
    printf("d10[%d] = %f\n", i, CPG_Result.dual->d10[i]);
  }
  for(i=0; i<7; i++) {
    printf("d11[%d] = %f\n", i, CPG_Result.dual->d11[i]);
  }
  for(i=0; i<7; i++) {
    printf("d12[%d] = %f\n", i, CPG_Result.dual->d12[i]);
  }
  for(i=0; i<7; i++) {
    printf("d13[%d] = %f\n", i, CPG_Result.dual->d13[i]);
  }
  for(i=0; i<15; i++) {
    printf("d14[%d] = %f\n", i, CPG_Result.dual->d14[i]);
  }
  for(i=0; i<15; i++) {
    printf("d15[%d] = %f\n", i, CPG_Result.dual->d15[i]);
  }
  for(i=0; i<49; i++) {
    printf("d16[%d] = %f\n", i, CPG_Result.dual->d16[i]);
  }
  for(i=0; i<36; i++) {
    printf("d17[%d] = %f\n", i, CPG_Result.dual->d17[i]);
  }
  for(i=0; i<15; i++) {
    printf("d18[%d] = %f\n", i, CPG_Result.dual->d18[i]);
  }

  return 0;

}
