function xdot = dynamics(t,in2,in3,in4)
%DYNAMICS
%    XDOT = DYNAMICS(T,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    17-Aug-2025 03:07:19

m1 = in2(7,:);
r1 = in2(1,:);
r2 = in2(2,:);
r3 = in2(3,:);
thrust_accel1 = in3(1,:);
thrust_accel2 = in3(2,:);
thrust_accel3 = in3(3,:);
v1 = in2(4,:);
v2 = in2(5,:);
v3 = in2(6,:);
t2 = r1.^2;
t3 = r2.^2;
t4 = r3.^2;
t5 = 1.0./m1;
t6 = t2+t3+t4;
t7 = 1.0./t6.^(3.0./2.0);
mt1 = [v1;v2;v3;-r1.*t7+t5.*thrust_accel1.*5.619649646535599e-2;-r2.*t7+t5.*thrust_accel2.*5.619649646535599e-2;-r3.*t7+t5.*thrust_accel3.*5.619649646535599e-2];
mt2 = [sqrt(thrust_accel1.^2+thrust_accel2.^2+thrust_accel3.^2).*(-4.26725757873853e-2)];
xdot = [mt1;mt2];
end
