/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * f_kepler_fixedtf.c
 *
 * Code generation for function 'f_kepler_fixedtf'
 *
 */

/* Include files */
#include "f_kepler_fixedtf.h"
#include "rt_nonfinite.h"
#include "mwmathutil.h"

/* Function Definitions */
void f_kepler_fixedtf(const real_T in2[7], const real_T in3[3], real_T xdot[7])
{
  real_T t5;
  real_T t7;
  /* F_KEPLER_FIXEDTF */
  /*     XDOT = F_KEPLER_FIXEDTF(T,IN2,IN3,IN4) */
  /*     This function was generated by the Symbolic Math Toolbox version 25.1.
   */
  /*     07-Sep-2025 00:01:12 */
  t5 = 1.0 / in2[6];
  t7 = 1.0 / muDoubleScalarPower(
                 (in2[0] * in2[0] + in2[1] * in2[1]) + in2[2] * in2[2], 1.5);
  xdot[0] = in2[3];
  xdot[1] = in2[4];
  xdot[2] = in2[5];
  xdot[3] = -in2[0] * t7 + t5 * in3[0] * 0.056196496465355988;
  xdot[4] = -in2[1] * t7 + t5 * in3[1] * 0.056196496465355988;
  xdot[5] = -in2[2] * t7 + t5 * in3[2] * 0.056196496465355988;
  xdot[6] = muDoubleScalarSqrt((in3[0] * in3[0] + in3[1] * in3[1]) +
                               in3[2] * in3[2]) *
            -0.0426725757873853;
}

/* End of code generation (f_kepler_fixedtf.c) */
