/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * integrate_error_discrete_FOH_kepler_fixedtf.c
 *
 * Code generation for function 'integrate_error_discrete_FOH_kepler_fixedtf'
 *
 */

/* Include files */
#include "integrate_error_discrete_FOH_kepler_fixedtf.h"
#include "A_kepler_fixedtf.h"
#include "f_kepler_fixedtf.h"
#include "rt_nonfinite.h"
#include "mwmathutil.h"
#include <emmintrin.h>
#include <string.h>

/* Function Definitions */
void STM_diff_eq_FOH(const real_T y[98], const real_T u[6], real_T ydot[98])
{
  __m128d r;
  __m128d r1;
  real_T A_t[49];
  real_T b_A_t[49];
  real_T c_y[49];
  real_T B_k_plusdot_tmp[21];
  real_T b_y[21];
  real_T c_A_t[21];
  real_T d_A_t[21];
  real_T xdot[7];
  real_T b_u[3];
  real_T t7;
  real_T t8;
  int32_T A_t_tmp;
  int32_T i;
  int32_T i2;
  int32_T i3;
  r = _mm_set1_pd(0.5);
  _mm_storeu_pd(&b_u[0], _mm_add_pd(_mm_mul_pd(_mm_loadu_pd(&u[0]), r),
                                    _mm_mul_pd(_mm_loadu_pd(&u[3]), r)));
  b_u[2] = u[2] * 0.5 + u[5] * 0.5;
  A_kepler_fixedtf(&y[0], b_u, A_t);
  /* B_kepler_fixedtf */
  /*     J_B = B_kepler_fixedtf(T,IN2,IN3,IN4) */
  /*     This function was generated by the Symbolic Math Toolbox version 25.1.
   */
  /*     07-Sep-2025 00:01:12 */
  t8 = 1.0 / y[6] * 0.056196496465355988;
  t7 = 1.0 / muDoubleScalarSqrt((b_u[0] * b_u[0] + b_u[1] * b_u[1]) +
                                b_u[2] * b_u[2]);
  f_kepler_fixedtf(&y[0], b_u, xdot);
  b_y[0] = 0.0;
  b_y[1] = 0.0;
  b_y[2] = 0.0;
  b_y[3] = t8;
  b_y[4] = 0.0;
  b_y[5] = 0.0;
  b_y[6] = t7 * b_u[0] * -0.0426725757873853;
  b_y[7] = 0.0;
  b_y[8] = 0.0;
  b_y[9] = 0.0;
  b_y[10] = 0.0;
  b_y[11] = t8;
  b_y[12] = 0.0;
  b_y[13] = t7 * b_u[1] * -0.0426725757873853;
  b_y[14] = 0.0;
  b_y[15] = 0.0;
  b_y[16] = 0.0;
  b_y[17] = 0.0;
  b_y[18] = 0.0;
  b_y[19] = t8;
  b_y[20] = t7 * b_u[2] * -0.0426725757873853;
  for (i = 0; i <= 18; i += 2) {
    r1 = _mm_loadu_pd(&b_y[i]);
    _mm_storeu_pd(&B_k_plusdot_tmp[i], _mm_mul_pd(r1, r));
  }
  B_k_plusdot_tmp[20] = b_y[20] * 0.5;
  memcpy(&c_y[0], &y[7], 49U * sizeof(real_T));
  memset(&b_A_t[0], 0, 49U * sizeof(real_T));
  for (i = 0; i < 7; i++) {
    int32_T b_A_t_tmp;
    int32_T i1;
    A_t_tmp = 7 * i + 2;
    i1 = 7 * i + 4;
    b_A_t_tmp = 7 * i + 6;
    for (i2 = 0; i2 < 7; i2++) {
      __m128d r2;
      t8 = c_y[i2 + 7 * i];
      r = _mm_loadu_pd(&A_t[7 * i2]);
      r1 = _mm_loadu_pd(&b_A_t[7 * i]);
      r2 = _mm_set1_pd(t8);
      _mm_storeu_pd(&b_A_t[7 * i], _mm_add_pd(r1, _mm_mul_pd(r, r2)));
      r = _mm_loadu_pd(&A_t[7 * i2 + 2]);
      r1 = _mm_loadu_pd(&b_A_t[A_t_tmp]);
      _mm_storeu_pd(&b_A_t[A_t_tmp], _mm_add_pd(r1, _mm_mul_pd(r, r2)));
      r = _mm_loadu_pd(&A_t[7 * i2 + 4]);
      r1 = _mm_loadu_pd(&b_A_t[i1]);
      _mm_storeu_pd(&b_A_t[i1], _mm_add_pd(r1, _mm_mul_pd(r, r2)));
      b_A_t[b_A_t_tmp] += A_t[7 * i2 + 6] * t8;
    }
  }
  memcpy(&b_y[0], &y[56], 21U * sizeof(real_T));
  for (i2 = 0; i2 < 7; i2++) {
    for (i3 = 0; i3 < 3; i3++) {
      t8 = 0.0;
      for (i = 0; i < 7; i++) {
        t8 += A_t[i2 + 7 * i] * b_y[i + 7 * i3];
      }
      A_t_tmp = i2 + 7 * i3;
      c_A_t[A_t_tmp] = t8 + B_k_plusdot_tmp[A_t_tmp];
    }
  }
  memcpy(&b_y[0], &y[77], 21U * sizeof(real_T));
  for (i2 = 0; i2 < 7; i2++) {
    for (i3 = 0; i3 < 3; i3++) {
      t8 = 0.0;
      for (i = 0; i < 7; i++) {
        t8 += A_t[i2 + 7 * i] * b_y[i + 7 * i3];
      }
      A_t_tmp = i2 + 7 * i3;
      d_A_t[A_t_tmp] = t8 + B_k_plusdot_tmp[A_t_tmp];
    }
    ydot[i2] = xdot[i2];
  }
  memcpy(&ydot[7], &b_A_t[0], 49U * sizeof(real_T));
  for (i = 0; i < 21; i++) {
    ydot[i + 56] = c_A_t[i];
    ydot[i + 77] = d_A_t[i];
  }
}

/* End of code generation (integrate_error_discrete_FOH_kepler_fixedtf.c) */
