/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 * File: A_kepler_fixedtf.c
 *
 * MATLAB Coder version            : 25.1
 * C/C++ source code generated on  : 07-Sep-2025 00:38:53
 */

/* Include Files */
#include "A_kepler_fixedtf.h"
#include "discretize_error_dynamics_FOH_kepler_fixedtf_rtwutil.h"
#include "rt_nonfinite.h"

/* Function Definitions */
/*
 * A_kepler_fixedtf
 *     J_A = A_kepler_fixedtf(T,IN2,IN3,IN4)
 *
 * Arguments    : const double in2[7]
 *                const double in3[3]
 *                double j_a[49]
 * Return Type  : void
 */
void A_kepler_fixedtf(const double in2[7], const double in3[3], double j_a[49])
{
  double t10;
  double t11;
  double t12;
  double t2;
  double t3;
  double t4;
  double t5;
  double t6;
  double t8;
  /*     This function was generated by the Symbolic Math Toolbox version 25.1.
   */
  /*     07-Sep-2025 00:01:12 */
  t2 = in2[0] * in2[0];
  t3 = in2[1] * in2[1];
  t4 = in2[2] * in2[2];
  t5 = 1.0 / (in2[6] * in2[6]);
  t6 = (t2 + t3) + t4;
  t8 = 1.0 / rt_powd_snf(t6, 2.5);
  t6 = -(1.0 / rt_powd_snf(t6, 1.5));
  t10 = in2[0] * in2[1] * t8 * 3.0;
  t11 = in2[0] * in2[2] * t8 * 3.0;
  t12 = in2[1] * in2[2] * t8 * 3.0;
  j_a[0] = 0.0;
  j_a[1] = 0.0;
  j_a[2] = 0.0;
  j_a[3] = t6 + t2 * t8 * 3.0;
  j_a[4] = t10;
  j_a[5] = t11;
  j_a[6] = 0.0;
  j_a[7] = 0.0;
  j_a[8] = 0.0;
  j_a[9] = 0.0;
  j_a[10] = t10;
  j_a[11] = t6 + t3 * t8 * 3.0;
  j_a[12] = t12;
  j_a[13] = 0.0;
  j_a[14] = 0.0;
  j_a[15] = 0.0;
  j_a[16] = 0.0;
  j_a[17] = t11;
  j_a[18] = t12;
  j_a[19] = t6 + t4 * t8 * 3.0;
  j_a[20] = 0.0;
  j_a[21] = 1.0;
  j_a[22] = 0.0;
  j_a[23] = 0.0;
  j_a[24] = 0.0;
  j_a[25] = 0.0;
  j_a[26] = 0.0;
  j_a[27] = 0.0;
  j_a[28] = 0.0;
  j_a[29] = 1.0;
  j_a[30] = 0.0;
  j_a[31] = 0.0;
  j_a[32] = 0.0;
  j_a[33] = 0.0;
  j_a[34] = 0.0;
  j_a[35] = 0.0;
  j_a[36] = 0.0;
  j_a[37] = 1.0;
  j_a[38] = 0.0;
  j_a[39] = 0.0;
  j_a[40] = 0.0;
  j_a[41] = 0.0;
  j_a[42] = 0.0;
  j_a[43] = 0.0;
  j_a[44] = 0.0;
  j_a[45] = t5 * in3[0] * -0.056196496465355988;
  j_a[46] = t5 * in3[1] * -0.056196496465355988;
  j_a[47] = t5 * in3[2] * -0.056196496465355988;
  j_a[48] = 0.0;
}

/*
 * File trailer for A_kepler_fixedtf.c
 *
 * [EOF]
 */
