
/*
Auto-generated by CVXPYgen on October 13, 2025 at 13:34:48.
Content: Example program for updating parameters, solving, and inspecting the result.
*/

#include <stdio.h>
#include "cpg_workspace.h"
#include "cpg_solve.h"

static int i;

int main(int argc, char *argv[]){

  // Update first entry of every user-defined parameter
  cpg_update_Ak_0(0, 0.93948633947000770306);
  cpg_update_Bk_minus_0(0, 0.00639210976459485269);
  cpg_update_Bk_plus_0(0, 0.00320078070306055885);
  cpg_update_ck(0, 0.22131248328800767755);
  cpg_update_Ak_1(0, 1.13960212480280675962);
  cpg_update_Bk_minus_1(0, 0.00679280177317159381);
  cpg_update_Bk_plus_1(0, 0.00332615213016343404);
  cpg_update_Ak_2(0, 1.30210994953043690536);
  cpg_update_Bk_minus_2(0, 0.00700574309031554848);
  cpg_update_Bk_plus_2(0, 0.00339652209527503213);
  cpg_update_Ak_3(0, 1.30634283361507685939);
  cpg_update_Bk_minus_3(0, 0.00703524206143431134);
  cpg_update_Bk_plus_3(0, 0.00342201088599367390);
  cpg_update_Ak_4(0, 1.18981681953299678334);
  cpg_update_Bk_minus_4(0, 0.00700133886036456189);
  cpg_update_Bk_plus_4(0, 0.00344485674800128119);
  cpg_update_Ak_5(0, 1.06541144323054792764);
  cpg_update_Bk_minus_5(0, 0.00699878891503248526);
  cpg_update_Bk_plus_5(0, 0.00348085868436287310);
  cpg_update_Ak_6(0, 1.00205526175810999412);
  cpg_update_Bk_minus_6(0, 0.00706749405600924554);
  cpg_update_Bk_plus_6(0, 0.00353371109709082728);
  cpg_update_Ak_7(0, 0.99188521779126959110);
  cpg_update_Bk_minus_7(0, 0.00719250839617017676);
  cpg_update_Bk_plus_7(0, 0.00359908241222267134);
  cpg_update_Ak_8(0, 0.99716336033166863562);
  cpg_update_Bk_minus_8(0, 0.00733785645262650249);
  cpg_update_Bk_plus_8(0, 0.00366993283118534786);
  cpg_update_Ak_9(0, 0.99972035862387120808);
  cpg_update_Bk_minus_9(0, 0.00748482123524154674);
  cpg_update_Bk_plus_9(0, 0.00374251316420189887);
  cpg_update_Ak_10(0, 1.00008778559414701625);
  cpg_update_Bk_minus_10(0, 0.00763450762648002889);
  cpg_update_Bk_plus_10(0, 0.00381722058512671755);
  cpg_update_Ak_11(0, 1.00040714679855780034);
  cpg_update_Bk_minus_11(0, 0.00779022770435952930);
  cpg_update_Bk_plus_11(0, 0.00389495440097157144);
  cpg_update_Ak_12(0, 1.00269862905295181754);
  cpg_update_Bk_minus_12(0, 0.00795568346769719853);
  cpg_update_Bk_plus_12(0, 0.00397674267684016737);
  cpg_update_Ak_13(0, 1.01098728789193526012);
  cpg_update_Bk_minus_13(0, 0.00813855471616085728);
  cpg_update_Bk_plus_13(0, 0.00406463596571488613);
  cpg_update_Ak_14(0, 1.01168696161410287537);
  cpg_update_Bk_minus_14(0, 0.00830909406506515243);
  cpg_update_Bk_plus_14(0, 0.00415102153895327477);
  cpg_update_Ak_15(0, 0.95150216073412097195);
  cpg_update_Bk_minus_15(0, 0.00835273792463919404);
  cpg_update_Bk_plus_15(0, 0.00420624936943529617);
  cpg_update_Ak_16(0, 0.88602891639419312231);
  cpg_update_Bk_minus_16(0, 0.00848801378724797599);
  cpg_update_Bk_plus_16(0, 0.00429475601358280008);
  cpg_update_Ak_17(0, 0.99145590314435305679);
  cpg_update_Bk_minus_17(0, 0.00904221675988551958);
  cpg_update_Bk_plus_17(0, 0.00449600690742482829);
  cpg_update_Ak_18(0, 1.20178832622347697701);
  cpg_update_Bk_minus_18(0, 0.00960625852234717886);
  cpg_update_Bk_plus_18(0, 0.00468109206801032435);
  cpg_update_Ak_19(0, 1.32102209533002357134);
  cpg_update_Bk_minus_19(0, 0.00987727089864190444);
  cpg_update_Bk_plus_19(0, 0.00478973240164304141);
  cpg_update_Ak_20(0, 1.27860097418224438748);
  cpg_update_Bk_minus_20(0, 0.00994581161809141197);
  cpg_update_Bk_plus_20(0, 0.00485261871504902732);
  cpg_update_Ak_21(0, 1.14810444394867539053);
  cpg_update_Bk_minus_21(0, 0.00997414079763238315);
  cpg_update_Bk_plus_21(0, 0.00492566842904434976);
  cpg_update_Ak_22(0, 1.03875744666072478140);
  cpg_update_Bk_minus_22(0, 0.01007774117912699739);
  cpg_update_Bk_plus_22(0, 0.00502342588847402849);
  cpg_update_Ak_23(0, 0.99510579823824085732);
  cpg_update_Bk_minus_23(0, 0.01028950252779939692);
  cpg_update_Bk_plus_23(0, 0.00514762902374825762);
  cpg_update_x_0(0, -0.16891175770814034762);
  cpg_update_x_f(0, 2.43500784394500069396);
  cpg_update_x_ref(0, -0.16891175770814037538);
  cpg_update_u_ref(0, 0.00001000000000000000);

  // Solve the problem instance
  cpg_solve();

  // Print objective function value
  printf("obj = %f\n", CPG_Result.info->obj_val);

  // Print primal solution
  for(i=0; i<75; i++) {
    printf("U[%d] = %f\n", i, CPG_Result.prim->U[i]);
  }
  for(i=0; i<168; i++) {
    printf("V[%d] = %f\n", i, CPG_Result.prim->V[i]);
  }
  for(i=0; i<7; i++) {
    printf("v_0[%d] = %f\n", i, CPG_Result.prim->v_0[i]);
  }
  for(i=0; i<6; i++) {
    printf("v_N[%d] = %f\n", i, CPG_Result.prim->v_N[i]);
  }
  for(i=0; i<25; i++) {
    printf("eta[%d] = %f\n", i, CPG_Result.prim->eta[i]);
  }
  for(i=0; i<175; i++) {
    printf("X[%d] = %f\n", i, CPG_Result.prim->X[i]);
  }
  for(i=0; i<3; i++) {
    printf("p[%d] = %f\n", i, CPG_Result.prim->p[i]);
  }

  // Print dual solution
  for(i=0; i<7; i++) {
    printf("d0[%d] = %f\n", i, CPG_Result.dual->d0[i]);
  }
  for(i=0; i<7; i++) {
    printf("d1[%d] = %f\n", i, CPG_Result.dual->d1[i]);
  }
  for(i=0; i<7; i++) {
    printf("d2[%d] = %f\n", i, CPG_Result.dual->d2[i]);
  }
  for(i=0; i<7; i++) {
    printf("d3[%d] = %f\n", i, CPG_Result.dual->d3[i]);
  }
  for(i=0; i<7; i++) {
    printf("d4[%d] = %f\n", i, CPG_Result.dual->d4[i]);
  }
  for(i=0; i<7; i++) {
    printf("d5[%d] = %f\n", i, CPG_Result.dual->d5[i]);
  }
  for(i=0; i<7; i++) {
    printf("d6[%d] = %f\n", i, CPG_Result.dual->d6[i]);
  }
  for(i=0; i<7; i++) {
    printf("d7[%d] = %f\n", i, CPG_Result.dual->d7[i]);
  }
  for(i=0; i<7; i++) {
    printf("d8[%d] = %f\n", i, CPG_Result.dual->d8[i]);
  }
  for(i=0; i<7; i++) {
    printf("d9[%d] = %f\n", i, CPG_Result.dual->d9[i]);
  }
  for(i=0; i<7; i++) {
    printf("d10[%d] = %f\n", i, CPG_Result.dual->d10[i]);
  }
  for(i=0; i<7; i++) {
    printf("d11[%d] = %f\n", i, CPG_Result.dual->d11[i]);
  }
  for(i=0; i<7; i++) {
    printf("d12[%d] = %f\n", i, CPG_Result.dual->d12[i]);
  }
  for(i=0; i<7; i++) {
    printf("d13[%d] = %f\n", i, CPG_Result.dual->d13[i]);
  }
  for(i=0; i<7; i++) {
    printf("d14[%d] = %f\n", i, CPG_Result.dual->d14[i]);
  }
  for(i=0; i<7; i++) {
    printf("d15[%d] = %f\n", i, CPG_Result.dual->d15[i]);
  }
  for(i=0; i<7; i++) {
    printf("d16[%d] = %f\n", i, CPG_Result.dual->d16[i]);
  }
  for(i=0; i<7; i++) {
    printf("d17[%d] = %f\n", i, CPG_Result.dual->d17[i]);
  }
  for(i=0; i<7; i++) {
    printf("d18[%d] = %f\n", i, CPG_Result.dual->d18[i]);
  }
  for(i=0; i<7; i++) {
    printf("d19[%d] = %f\n", i, CPG_Result.dual->d19[i]);
  }
  for(i=0; i<7; i++) {
    printf("d20[%d] = %f\n", i, CPG_Result.dual->d20[i]);
  }
  for(i=0; i<7; i++) {
    printf("d21[%d] = %f\n", i, CPG_Result.dual->d21[i]);
  }
  for(i=0; i<7; i++) {
    printf("d22[%d] = %f\n", i, CPG_Result.dual->d22[i]);
  }
  for(i=0; i<7; i++) {
    printf("d23[%d] = %f\n", i, CPG_Result.dual->d23[i]);
  }
  for(i=0; i<25; i++) {
    printf("d24[%d] = %f\n", i, CPG_Result.dual->d24[i]);
  }
  for(i=0; i<25; i++) {
    printf("d25[%d] = %f\n", i, CPG_Result.dual->d25[i]);
  }
  printf("d26 = %f\n", CPG_Result.dual->d26);
  for(i=0; i<9; i++) {
    printf("d27[%d] = %f\n", i, CPG_Result.dual->d27[i]);
  }
  for(i=0; i<9; i++) {
    printf("d28[%d] = %f\n", i, CPG_Result.dual->d28[i]);
  }
  printf("d29 = %f\n", CPG_Result.dual->d29);
  for(i=0; i<36; i++) {
    printf("d30[%d] = %f\n", i, CPG_Result.dual->d30[i]);
  }
  for(i=0; i<25; i++) {
    printf("d31[%d] = %f\n", i, CPG_Result.dual->d31[i]);
  }

  return 0;

}
