
/*
Auto-generated by CVXPYgen on October 13, 2025 at 13:34:48.
Content: Declarations for Python binding with pybind11.
*/

// User-defined parameters
struct CPG_Params_cpp_t {
    std::array<double, 49> Ak_0;
    std::array<double, 21> Bk_minus_0;
    std::array<double, 21> Bk_plus_0;
    std::array<double, 168> ck;
    std::array<double, 49> Ak_1;
    std::array<double, 21> Bk_minus_1;
    std::array<double, 21> Bk_plus_1;
    std::array<double, 49> Ak_2;
    std::array<double, 21> Bk_minus_2;
    std::array<double, 21> Bk_plus_2;
    std::array<double, 49> Ak_3;
    std::array<double, 21> Bk_minus_3;
    std::array<double, 21> Bk_plus_3;
    std::array<double, 49> Ak_4;
    std::array<double, 21> Bk_minus_4;
    std::array<double, 21> Bk_plus_4;
    std::array<double, 49> Ak_5;
    std::array<double, 21> Bk_minus_5;
    std::array<double, 21> Bk_plus_5;
    std::array<double, 49> Ak_6;
    std::array<double, 21> Bk_minus_6;
    std::array<double, 21> Bk_plus_6;
    std::array<double, 49> Ak_7;
    std::array<double, 21> Bk_minus_7;
    std::array<double, 21> Bk_plus_7;
    std::array<double, 49> Ak_8;
    std::array<double, 21> Bk_minus_8;
    std::array<double, 21> Bk_plus_8;
    std::array<double, 49> Ak_9;
    std::array<double, 21> Bk_minus_9;
    std::array<double, 21> Bk_plus_9;
    std::array<double, 49> Ak_10;
    std::array<double, 21> Bk_minus_10;
    std::array<double, 21> Bk_plus_10;
    std::array<double, 49> Ak_11;
    std::array<double, 21> Bk_minus_11;
    std::array<double, 21> Bk_plus_11;
    std::array<double, 49> Ak_12;
    std::array<double, 21> Bk_minus_12;
    std::array<double, 21> Bk_plus_12;
    std::array<double, 49> Ak_13;
    std::array<double, 21> Bk_minus_13;
    std::array<double, 21> Bk_plus_13;
    std::array<double, 49> Ak_14;
    std::array<double, 21> Bk_minus_14;
    std::array<double, 21> Bk_plus_14;
    std::array<double, 49> Ak_15;
    std::array<double, 21> Bk_minus_15;
    std::array<double, 21> Bk_plus_15;
    std::array<double, 49> Ak_16;
    std::array<double, 21> Bk_minus_16;
    std::array<double, 21> Bk_plus_16;
    std::array<double, 49> Ak_17;
    std::array<double, 21> Bk_minus_17;
    std::array<double, 21> Bk_plus_17;
    std::array<double, 49> Ak_18;
    std::array<double, 21> Bk_minus_18;
    std::array<double, 21> Bk_plus_18;
    std::array<double, 49> Ak_19;
    std::array<double, 21> Bk_minus_19;
    std::array<double, 21> Bk_plus_19;
    std::array<double, 49> Ak_20;
    std::array<double, 21> Bk_minus_20;
    std::array<double, 21> Bk_plus_20;
    std::array<double, 49> Ak_21;
    std::array<double, 21> Bk_minus_21;
    std::array<double, 21> Bk_plus_21;
    std::array<double, 49> Ak_22;
    std::array<double, 21> Bk_minus_22;
    std::array<double, 21> Bk_plus_22;
    std::array<double, 49> Ak_23;
    std::array<double, 21> Bk_minus_23;
    std::array<double, 21> Bk_plus_23;
    std::array<double, 7> x_0;
    std::array<double, 6> x_f;
    std::array<double, 175> x_ref;
    std::array<double, 75> u_ref;
};

// Flags for updated user-defined parameters
struct CPG_Updated_cpp_t {
    bool Ak_0;
    bool Bk_minus_0;
    bool Bk_plus_0;
    bool ck;
    bool Ak_1;
    bool Bk_minus_1;
    bool Bk_plus_1;
    bool Ak_2;
    bool Bk_minus_2;
    bool Bk_plus_2;
    bool Ak_3;
    bool Bk_minus_3;
    bool Bk_plus_3;
    bool Ak_4;
    bool Bk_minus_4;
    bool Bk_plus_4;
    bool Ak_5;
    bool Bk_minus_5;
    bool Bk_plus_5;
    bool Ak_6;
    bool Bk_minus_6;
    bool Bk_plus_6;
    bool Ak_7;
    bool Bk_minus_7;
    bool Bk_plus_7;
    bool Ak_8;
    bool Bk_minus_8;
    bool Bk_plus_8;
    bool Ak_9;
    bool Bk_minus_9;
    bool Bk_plus_9;
    bool Ak_10;
    bool Bk_minus_10;
    bool Bk_plus_10;
    bool Ak_11;
    bool Bk_minus_11;
    bool Bk_plus_11;
    bool Ak_12;
    bool Bk_minus_12;
    bool Bk_plus_12;
    bool Ak_13;
    bool Bk_minus_13;
    bool Bk_plus_13;
    bool Ak_14;
    bool Bk_minus_14;
    bool Bk_plus_14;
    bool Ak_15;
    bool Bk_minus_15;
    bool Bk_plus_15;
    bool Ak_16;
    bool Bk_minus_16;
    bool Bk_plus_16;
    bool Ak_17;
    bool Bk_minus_17;
    bool Bk_plus_17;
    bool Ak_18;
    bool Bk_minus_18;
    bool Bk_plus_18;
    bool Ak_19;
    bool Bk_minus_19;
    bool Bk_plus_19;
    bool Ak_20;
    bool Bk_minus_20;
    bool Bk_plus_20;
    bool Ak_21;
    bool Bk_minus_21;
    bool Bk_plus_21;
    bool Ak_22;
    bool Bk_minus_22;
    bool Bk_plus_22;
    bool Ak_23;
    bool Bk_minus_23;
    bool Bk_plus_23;
    bool x_0;
    bool x_f;
    bool x_ref;
    bool u_ref;
};

// Primal solution
struct CPG_Prim_cpp_t {
    std::array<double, 75> U;
    std::array<double, 168> V;
    std::array<double, 7> v_0;
    std::array<double, 6> v_N;
    std::array<double, 25> eta;
    std::array<double, 175> X;
    std::array<double, 3> p;
};

// Dual solution
struct CPG_Dual_cpp_t {
    std::array<double, 7> d0;
    std::array<double, 7> d1;
    std::array<double, 7> d2;
    std::array<double, 7> d3;
    std::array<double, 7> d4;
    std::array<double, 7> d5;
    std::array<double, 7> d6;
    std::array<double, 7> d7;
    std::array<double, 7> d8;
    std::array<double, 7> d9;
    std::array<double, 7> d10;
    std::array<double, 7> d11;
    std::array<double, 7> d12;
    std::array<double, 7> d13;
    std::array<double, 7> d14;
    std::array<double, 7> d15;
    std::array<double, 7> d16;
    std::array<double, 7> d17;
    std::array<double, 7> d18;
    std::array<double, 7> d19;
    std::array<double, 7> d20;
    std::array<double, 7> d21;
    std::array<double, 7> d22;
    std::array<double, 7> d23;
    std::array<double, 25> d24;
    std::array<double, 25> d25;
    double d26;
    std::array<double, 9> d27;
    std::array<double, 9> d28;
    double d29;
    std::array<double, 36> d30;
    std::array<double, 25> d31;
};

// Solver information
struct CPG_Info_cpp_t {
    double obj_val;
    int iter;
    int status;
    double pri_res;
    double dua_res;
    double time;
};

// Solution and solver information
struct CPG_Result_cpp_t {
    CPG_Prim_cpp_t prim;
    CPG_Dual_cpp_t dual;
    CPG_Info_cpp_t info;
};

// Main solve function
CPG_Result_cpp_t solve_cpp(struct CPG_Updated_cpp_t& CPG_Updated_cpp, struct CPG_Params_cpp_t& CPG_Params_cpp);
