function j_a = A_kepler_fixedtf(t,in2,in3,in4)
%A_kepler_fixedtf
%    J_A = A_kepler_fixedtf(T,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    07-Sep-2025 00:01:12

m1 = in2(7,:);
r1 = in2(1,:);
r2 = in2(2,:);
r3 = in2(3,:);
thrust_accel1 = in3(1,:);
thrust_accel2 = in3(2,:);
thrust_accel3 = in3(3,:);
t2 = r1.^2;
t3 = r2.^2;
t4 = r3.^2;
t5 = 1.0./m1.^2;
t6 = t2+t3+t4;
t7 = 1.0./t6.^(3.0./2.0);
t8 = 1.0./t6.^(5.0./2.0);
t9 = -t7;
t10 = r1.*r2.*t8.*3.0;
t11 = r1.*r3.*t8.*3.0;
t12 = r2.*r3.*t8.*3.0;
j_a = reshape([0.0,0.0,0.0,t9+t2.*t8.*3.0,t10,t11,0.0,0.0,0.0,0.0,t10,t9+t3.*t8.*3.0,t12,0.0,0.0,0.0,0.0,t11,t12,t9+t4.*t8.*3.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t5.*thrust_accel1.*(-5.619649646535599e-2),t5.*thrust_accel2.*(-5.619649646535599e-2),t5.*thrust_accel3.*(-5.619649646535599e-2),0.0],[7,7]);
end
