function j_b = B_kepler_fixedtf(t,in2,in3,in4)
%B_kepler_fixedtf
%    J_B = B_kepler_fixedtf(T,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    07-Sep-2025 00:01:12

m1 = in2(7,:);
thrust_accel1 = in3(1,:);
thrust_accel2 = in3(2,:);
thrust_accel3 = in3(3,:);
t2 = thrust_accel1.^2;
t3 = thrust_accel2.^2;
t4 = thrust_accel3.^2;
t5 = 1.0./m1;
t6 = t2+t3+t4;
t8 = t5.*5.619649646535599e-2;
t7 = 1.0./sqrt(t6);
mt1 = [0.0,0.0,0.0,t8,0.0,0.0,t7.*thrust_accel1.*(-4.26725757873853e-2),0.0,0.0,0.0,0.0,t8,0.0,t7.*thrust_accel2.*(-4.26725757873853e-2),0.0,0.0,0.0,0.0,0.0,t8];
mt2 = [t7.*thrust_accel3.*(-4.26725757873853e-2)];
j_b = reshape([mt1,mt2],7,3);
end
