function xdot = dynamics_modified_equinoctial(t,in2,in3,in4)
%DYNAMICS_MODIFIED_EQUINOCTIAL
%    XDOT = DYNAMICS_MODIFIED_EQUINOCTIAL(T,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    31-Aug-2025 11:19:26

m1 = in2(7,:);
thrust1 = in3(1,:);
thrust2 = in3(2,:);
thrust3 = in3(3,:);
x_me1 = in2(1,:);
x_me2 = in2(2,:);
x_me3 = in2(3,:);
x_me4 = in2(4,:);
x_me5 = in2(5,:);
x_me6 = in2(6,:);
t2 = cos(x_me6);
t3 = sin(x_me6);
t4 = x_me4.^2;
t5 = x_me5.^2;
t10 = 1.0./m1;
t13 = sqrt(x_me1);
t6 = t2.*x_me2;
t7 = t2.*x_me5;
t8 = t3.*x_me3;
t9 = t3.*x_me4;
t15 = t4+t5+1.0;
t11 = t6.*2.0;
t12 = t8.*2.0;
t14 = -t9;
t16 = t6+t8+1.0;
t17 = t16+1.0;
t18 = t7+t14;
t19 = t11+t12+2.0;
t20 = 1.0./t16;
t21 = 1.0./t19;
mt1 = [t10.*t13.^3.*t20.*thrust2.*1.12392992930712e-1;t3.*t10.*t13.*thrust1.*5.619649646535599e-2+t10.*t13.*t20.*thrust2.*(x_me2+t2.*t17).*5.619649646535599e-2+t10.*t13.*t18.*t20.*thrust3.*x_me3.*5.619649646535599e-2];
mt2 = [t2.*t10.*t13.*thrust1.*(-5.619649646535599e-2)+t10.*t13.*t20.*thrust2.*(x_me3+t3.*t17).*5.619649646535599e-2-t10.*t13.*t18.*t20.*thrust3.*x_me2.*5.619649646535599e-2;t2.*t10.*t13.*t15.*t21.*thrust3.*5.619649646535599e-2];
mt3 = [t3.*t10.*t13.*t15.*t21.*thrust3.*5.619649646535599e-2;1.0./t13.^3.*1.0./t20.^2-t10.*t13.*t18.*t20.*thrust3.*5.619649646535599e-2;sqrt(thrust1.^2+thrust2.^2+thrust3.^2).*(-4.26725757873853e-2)];
xdot = [mt1;mt2;mt3];
end
